---
name: CI

on:
  pull_request:
    branches: master
  push:
    branches: master

# Defaults for building KLEE
env:
  BASE_IMAGE: ubuntu:jammy-20230126
  REPOSITORY: ghcr.io/klee
  COVERAGE: 0
  DISABLE_ASSERTIONS: 0
  ENABLE_DOXYGEN: 0
  ENABLE_OPTIMIZED: 1
  ENABLE_DEBUG: 1
  GTEST_VERSION: 1.16.0
  KLEE_RUNTIME_BUILD: "Debug+Asserts"
  LLVM_VERSION: 13
  MINISAT_VERSION: "master"
  REQUIRES_RTTI: 0
  SOLVERS: STP:Z3
  STP_VERSION: 2.3.3
  TCMALLOC_VERSION: 2.9.1
  UCLIBC_VERSION: klee_uclibc_v1.4
  USE_TCMALLOC: 1
  USE_LIBCXX: 1
  Z3_VERSION: 4.8.15
  SQLITE_VERSION: 3400100

jobs:
  Linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [
          "STP master",
        ]
        include:
          # Test we can build against STP master
          - name: "STP master"
            env:
              SOLVERS: STP
              STP_VERSION: master
    steps:
      - name: Checkout KLEE source code
        uses: actions/checkout@v4
      - name: Build KLEE
        env: ${{ matrix.env }}
        run: scripts/build/build.sh klee --docker --create-final-image
      - name: Run tests
        run: | # XXX: Workaround for https://github.com/llvm/llvm-project/issues/78354
             sudo sysctl vm.mmap_rnd_bits=28
             scripts/build/run-tests.sh --run-docker --debug

  macOS:
    runs-on: macos-latest
    env:
      LLVM_VERSION: 14
      BASE: /tmp
      SOLVERS: Z3
      UCLIBC_VERSION: 0
      USE_TCMALLOC: 0
      USE_LIBCXX: 0
    steps:
      - name: Install newer version of Bash
        run: brew install bash
      - name: Checkout KLEE source code
        uses: actions/checkout@v4
      - name: Create virtualenv for Python3 (PEP 668)
        run:  python3 -m venv .venv
      - name: Build KLEE
        run:  source .venv/bin/activate && echo "$(which tabulate)" && scripts/build/build.sh klee --debug --install-system-deps
      - name: Run tests
        run:  source .venv/bin/activate && scripts/build/run-tests.sh /tmp/klee_build* --debug

  Docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout KLEE Code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build .

  Coverage:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        name: [
          "STP",
          "Z3",
        ]
        include:
          - name: "STP"
            env:
              SOLVERS: STP:Z3
          - name: "Z3"
            env:
              SOLVERS: Z3
    env:
      ENABLE_OPTIMIZED: 0
      COVERAGE: 1
    steps:
      - name: Checkout KLEE source code
        uses: actions/checkout@v4
        with:
          # Codecov may run into "Issue detecting commit SHA. Please run
          # actions/checkout with fetch-depth > 1 or set to 0" when uploading.
          # See also https://github.com/codecov/codecov-action/issues/190
          fetch-depth: 2
      - name: Build KLEE
        env: ${{ matrix.env }}
        run: scripts/build/build.sh klee --docker --create-final-image
      - name: Run tests
        run: scripts/build/run-tests.sh --coverage --upload-coverage --run-docker --debug
